export { Router } from './router.js'
export type { RouterDeps, RouteRequest, RouteResult, RouteAction } from './router.js'
export { ControlPlane, hubRpcHandlers, rpcError } from './control-plane.js'
export type { ControlPlaneOptions, NodeConnection, PairingConsumer } from './control-plane.js'
export { HubConnection } from './connection.js'
export type { HubConnectionOptions } from './connection.js'
export { HealthAggregator } from './health.js'
export type { HealthAggregatorDeps, NodeHealthSummary } from './health.js'
export { MeshServer } from './mesh.js'
export type { MeshServerOptions } from './mesh.js'
export { HubMcpServer } from './mcp/server.js'
export type { HubMcpServerOptions, McpToolCall, McpCallResult, WriteForwarder } from './mcp/server.js'
export { TOOLS, TOOL_BY_NAME, COMPAT_TOOLS, WRITE_TOOLS } from './mcp/tools.js'
export type { ToolDef } from './mcp/tools.js'
export { PairingService, DEFAULT_PAIRING_TTL_MS, DEFAULT_MAX_FAILURES, DEFAULT_RATE_LIMIT } from './pairing.js'
export type { PairingOptions, PairingConsumeResult, PairingFailReason, PairingCodeRow } from './pairing.js'
export { HubHa, electLeader, judgeTerm, mergeRegistryEntries, registryDiff, derivePeerMcpUrl, mcpCallLeader, QUORUM_LOST_ERROR } from './ha.js'
export type { HubHaDeps, HaNode, Candidate, TermJudgment, MergeResult, HaPhase, HaWriteMode, WebSocketLike as HaWebSocketLike } from './ha.js'